version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - COOLIFY_API_URL=https://coolify.ok2.com
      - COOLIFY_API_TOKEN=1|YSwELH9ZYTe3RAuBZoui1x44PoGKu4HwjCEjJijJb92a4edd
    networks:
      - internal

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - internal

networks:
  internal:
    driver: bridge
